# -*- coding: utf-8 -*-
"""BPP-01_DataAnalysis&Visualize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GsZwxAPtQTJGrlpLlePzDC-G5yGVSF71
"""

import pandas as pd
import matplotlib.pyplot as plt

!wget https://raw.githubusercontent.com/Abdullahfoysal/pp11-Project-AnalyzeAndVisualize/refs/heads/main/student_data.csv

#import student database from drive
df = pd.read_csv("student_data.csv")
df.head()
df.sample(10)

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("student_data.csv")

num_bangladesh_students = df[df['country'] == 'Bangladesh'].shape[0]
print(f"Number of students from Bangladesh: {num_bangladesh_students}")

#Calculate the average attendance for students in the "Information Technology" department

avg_attendance_it = df[df['department'] == 'Information Technology']['attendance'].mean()
print(f"Average attendance for IT department: {avg_attendance_it}")

#display students above cgpa 3.5 and study abroad

filtered = df[(df["cgpa"] > 3.5) & (df["abroad_study"] == "Yes")]
print("filtered:", filtered)

#Fill missing values in the "abroad_study" column with "No"

df['abroad_study'].fillna('No', inplace=True